[Interface]
# Client Private Key
PrivateKey = <CLIENT_PRIVATE_KEY>
# In-tunnel assigned IP
Address = 172.16.0.2/32, 2606:4700:110::/128
DNS = 1.1.1.1, 1.0.0.1
MTU = 1280

[Peer]
# Server Public Key
PublicKey = <SERVER_PUBLIC_KEY>
AllowedIPs = 0.0.0.0/0, ::/0
# Gateway Endpoint
Endpoint = <SERVER_HOST_OR_IP>:<PORT>
